src/pages/api/v1/overallStats/index.ts
src/server/trpc/router/_app.ts
src/server/trpc/router/overallStats.ts
src/types/overallstats.trpc.ts
src/utils/api/sumstats.helper.ts

This PR includes backend code only, so no side effects expected.

add overall statistics

---

src/pages/api/auth/[...nextauth].ts
src/pages/bribeform.tsx
src/server/trpc/router/_app.ts
src/server/trpc/router/bribes.ts

to test navigate to `http://localhost:3000/bribeform`
test with an user in the authenticated list, and one not (if you happen to have another github login)
check for flaws in authentication code on bribeform.tsx
```
if (
session &&
status === "authenticated" &&
userlist.includes(session?.user?.name || "")
) {
```

Add Sign in and Sign out Buttons 

---

package-lock.json
src/utils/api/bribeApr.helper.ts
src/utils/database/apikeys.db.ts
src/utils/database/bribefile.db.ts
src/utils/database/chartdata.db.ts
src/utils/database/config.db.ts
src/utils/database/loginID.db.ts
src/utils/externalData/beetsBack.ts
src/utils/externalData/coingecko.ts
src/utils/externalData/ftmScan.ts
src/utils/externalData/snapshot.ts
src/utils/externalData/theGraph.ts

- added a few more try..catch blocks
- added errorlogging
- updated "json5" npm package due to severe vulnerability warning

add Errorlogging, update faulty package dependency

---

src/pages/admin.tsx
src/server/trpc/router/loginId.ts
src/utils/api/editBribedata.ts
src/utils/api/semVer.helper.ts
src/utils/database/apikeys.db.ts

- auto set version number on bribefile changes
- add admin function to add new apikey into database

Admin backend

---

package-lock.json
package.json
src/pages/_app.tsx
src/pages/bribeform.tsx
src/styles/theme.ts

updated font to Inter from Raleway. Because raleway is difficult to read, especially the numbers.

updated to inter font

---

src/pages/round/[...number].tsx

formatted some of the card on the main page. not finished

update card format

---

src/pages/test-backend.tsx
src/server/trpc/router/bribedata.ts

fix bribedata router

---

src/components/TopRow.tsx

fix top row navigation

---

src/components/DashboardCard.tsx
src/components/DashboardGrid.tsx
src/components/dashboardTemp.tsx
src/pages/bribersDashboard.tsx
src/server/trpc/router/bribersDashboard.ts
src/types/bribelist.trpc.ts
src/types/bribersDashboard.trpc.ts
src/types/card.component.ts
src/utils/api/bribedata.helper.ts
src/utils/api/bribersDashboard.helper.ts
src/utils/database/bribeDashboard.db.ts

This reverts commit f16840cc36ab8b92f305a5f27c07a66b088789b0.

Revert "Revert "Bribers dashboard raw version""

---

src/components/TableView.tsx
src/pages/round/[...number].tsx

- chose the right datafields to display
- make a sort function with clickable headings
- moved to a component

66 improve voter dashboard table view

---

src/components/SplashItem.tsx
src/hooks/useVoteState.ts
src/pages/index.tsx
src/pages/round/[...number].tsx

- voter's dashboard page will refresh during active vote 
- not redirecting from splash page, but added indicator 
- WIP but usable

vote state handling, issue #69

---

src/components/TopRow.tsx

- fix #73 
- simple, effective
- alignments not optimal but will do for now

wrap top row items

---

src/pages/chart/index.tsx

chart colormodes

---

src/components/Footer.tsx
src/components/Summary.tsx
src/components/TableView.tsx
src/pages/chart/index.tsx
src/pages/index.tsx
src/pages/round/[...number].tsx
src/pages/snapshotTimes/index.tsx

footer links, $/kVP, table alignment

---

src/components/DashboardCard.tsx
src/components/DashboardGrid.tsx
src/pages/bribersDashboard.tsx
src/server/trpc/router/bribersDashboard.ts
src/types/bribersDashboard.trpc.ts
src/types/emission.raw.ts
src/utils/api/bribeApr.helper.ts
src/utils/api/bribersDashboard.helper.ts
src/utils/externalData/theGraph.ts

closes #75 
- change card styling to fit voters dashboard
- make it responsive
- bring back loading animation
- fix theGraph error (over limit) by diverting to slower but unlimited RPC method if failed
- add total bribes to the bribers common dashboard
- some cleanup

75 UI fixes for bribers dashboard

---

src/hooks/useVoteState.ts
src/pages/round/[...number].tsx

calculate and display VP

---

src/components/TableView.tsx

fix issue #98 table view

---

src/components/Summary.tsx
src/components/TopRow.tsx
src/pages/chart/index.tsx
src/pages/round/[...number].tsx

fix #102 
update number in URL when switching rounds
should now also address all possible cases when requesting /round in URL:
/round
/round/
/round/$validnumber
/round/$invalidnumber
/round/$anythingNOTnumber

fix #102 url params/route rewrite

---

src/components/EditOffer/EditOfferModal.tsx
src/components/EditOffer/Reward.tsx
src/components/EditRound/EditRound.tsx
src/pages/admin.tsx
src/pages/bribeform.tsx
src/pages/editVotablePools.tsx
src/server/trpc/router/roundlist.ts
src/utils/api/bribedata.helper.ts
src/utils/api/bribersDashboard.helper.ts

- fix editVotablePools: remove round selector and add useEffect to refresh
- work on admin page: remove round selector and add 2 buttons to call other forms
- bribeform: remove round selector, add callback functions for modals
- editOfferModal: move functions to bribeform, fix other things around this
- Reward component: add empty string to selector to ensure, onChange is always triggered.

Small fixes

---

src/components/EditOffer/EditOfferModal.tsx
src/pages/bribeform.tsx
src/pages/test-backend.tsx
src/server/trpc/router/bribedata.ts
src/utils/api/editBribedata.ts

- add "suggestion" feature to add offer form
- add a suggestToken endpoint to tRPC to get a list of tokens used in previous round

Form add suggestions

---

src/components/EditOffer/EditOfferModal.tsx
src/components/EditRound/EditRound.tsx
src/components/EditToken/DeleteTokenModal.tsx
src/components/EditToken/EditToken.tsx
src/pages/bribeform.tsx
src/pages/test-backend.tsx
src/server/trpc/router/bribedata.ts
src/utils/api/editBribedata.ts

create forms to add, edit and delete tokendata

Token form

---

src/components/EditOffer/EditOfferModal.tsx
src/components/EditOffer/Reward.tsx
src/components/EditToken/EditToken.tsx
src/components/Header.tsx

all forms fixed

---

src/utils/api/emission.helper.ts

fixes #104 
- fix temp variable to reach termination condition

fix emission change finder

---

src/components/Summary.tsx
src/components/TableView.tsx
src/pages/gaugeVoteHistory/index.tsx
src/pages/round/[...number].tsx

Updated labels for maBEETS ...

update 1000 vp labels

---

src/components/CustomConnectButton.tsx
src/components/Summary.tsx
src/components/TopRow.tsx
src/pages/round/[...number].tsx
src/utils/api/chartdata.helper.ts

- Added help text to connect button. Any suggestions on wording. chatgpt gave a hand on that one.
- Removed extra <Center> tags as the most containers have align attributes
- update a few locale that I missed in previous change

Add help text to connect button. Misc fixes

---

src/components/MergeRelicModal.tsx
src/components/SplitRelicModal.tsx
src/hooks/useSplitRelic.ts

actually fixed the split amount zero problem. Split button should be disable when amount is 0

Split function, can submit transaction with amount zero

---

src/utils/externalData/beetsBack.ts

change backend url

---

src/utils/api/bribeApr.helper.ts
src/utils/api/cron.helper.ts

fixed filter in cron.helper.ts
added calc for ext. bribes ROI

calculate ext. ROI

---

src/pages/api/v1/cron/voteEnd.ts
src/pages/editVotablePools.tsx
src/types/votablePools.raw.ts
src/utils/api/bribersDashboard.helper.ts
src/utils/api/votablePools.helper.ts

Backend part for variable cap percentage entries. Adds capPercentage to votablePool data.
Frontend (src/pages/editVotablePools.tsx) yet to be done.

various vote cap values - backend part

---

src/pages/editVotablePools.tsx

Update Edit Votable Pool to include Cap Multiplier Input

---

src/pages/editVotablePools.tsx
src/utils/externalData/beetsBack.ts

- add chain parameter to beetsBack.ts
- add eslint annotation to editVotablePools.tsx (to avoid errormessages on dev environment)

fix chain param

---

src/utils/externalData/liveRpcQueries.ts

Add error handling to RPC price feed

Error handling for RPC pricefeed

---

src/utils/externalData/beetsBack.ts
src/utils/externalData/pricefeed.ts

add pricefeed method to retrieve single token price from beethoven-x backend

add beetsBack pricefeed single token

---

src/components/EditOffer/EditOfferModal.tsx
src/pages/api/v1/cron/hiddenhand.ts
src/pages/api/v1/temp/index.ts
src/types/bribedata.raw.ts
src/types/hiddenhand.raw.ts
src/utils/api/bribedata.helper.ts
src/utils/api/editBribedata.ts
src/utils/api/hiddenhand.helper.ts
src/utils/externalData/hiddenhand.ts
src/utils/externalData/pricefeed.ts

closes #128 
Hiddenhand importer reads API data from hiddenhand on every call, compares to already registered data and adds in missing parts.

Hiddenhand

---

src/pages/api/v1/cron/hiddenhand.ts
src/pages/api/v1/temp/index.ts
src/utils/api/hiddenhand.helper.ts
vercel.json

- Add special treatment for bb-ftmmen
- Add Cron Tab entry
- make hiddenhand endpoint more cron resistant (don't run after vote end)

New reward token & CronJob

---

src/utils/externalData/beetsBack.ts

please check, but I think this is not an array.

bugfix: remove array brackets

---

src/utils/externalData/theGraph.ts

fix Graph QL endpoints, divert to RPC where not available.

fix theGraph

---

.env.example
src/utils/externalData/theGraph.ts

- switch endpoint URL for theGraph
- some cleanup

TheGraph endpoint for blocks

---

src/utils/externalData/theGraph.ts

fix theGraph url

---

src/types/theGraph.raw.ts
src/utils/externalData/theGraph.ts

Fixes the issue with graph-ql user query limited to 5000 entries.

fix-graphql

---

src/utils/externalData/theGraph.ts

dealing with cronjob issues again

new fix for theGraph

---

src/components/EditRound/EditRound.tsx
src/pages/api/v1/cron/snapshot.ts
src/pages/api/v1/temp/index.ts
src/pages/bribeform.tsx
src/pages/bribersDashboard.tsx
src/types/bribedata.raw.ts
src/types/bribersDashboard.trpc.ts
src/types/snapshot.raw.ts
src/utils/api/bribeApr.helper.ts
src/utils/api/bribersDashboard.helper.ts
src/utils/api/cron.helper.ts
src/utils/api/emission.helper.ts
src/utils/api/hiddenhand.helper.ts
src/utils/api/round.helper.ts
src/utils/externalData/snapshot.ts
src/utils/externalData/theGraph.ts

* Re-enable briber's dashboard
* remove fantom related stuff
* remove "prediction" mode, as emission schedule no longer relies on beets per block and blockspeed
* remove unused UI elements
* add emission fetch from github for automatic vote end

Bribers Dashboard on Sonic
